version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
    - "50432"
    ports:
      - "50432:50432"
    volumes:
      - sgp_data:/var/lib/postgresql/data
    command: -p 50432

volumes:
  sgp_data:
